function [ A_MMSE,Beta ] = MMSE( H,K,Ptr )

% A : Linear Precoding Matrix
% B : Scalar of Wiener filter

% MMSE precoding is the optimal linear precoding in MU-MIMO downlink system.
% This technique is generated by the mean square error (MSE) method. Owing to
% average power at each transmitted antenna is constrained, Lagrangian optimization
% method is used for obtaining this precoder

I=eye(K);

B = conj(H) * (H.'* conj(H) + K/Ptr*I)^(-1);

Beta = sqrt(trace(B*B')/Ptr);

A_MMSE = 1/Beta * conj(H) * (H.'* conj(H) + K/Ptr*I)^(-1);   %H.' = nonconjugate transpose

end


